### ISSUE TITLE
NoMethodError: undefined method `line' for #<Pronto::BundlerAudit::Results::ProntoMessagesAdapter::DeepLine:0x000055575ca4ddd8>

### ISSUE THREAD

**Issue by ineluki00** [pdobb/pronto-bundler_audit#11]
Hi,

i am trying to integrate pronto in gitlab-ci but getting the following error:

```bash
$ bundle exec pronto list
brakeman
bundler_audit
fasterer
flay
reek
rubocop
$ bundle exec pronto run -f gitlab_mr -c origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
bundler: failed to load command: pronto (/usr/local/bundle/bin/pronto)
NoMethodError: undefined method `line' for #<Pronto::BundlerAudit::Results::ProntoMessagesAdapter::DeepLine:0x000055575ca4ddd8>
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/gitlab_merge_request_review_formatter.rb:25:in `line_number'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:70:in `new_comment'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:77:in `block in new_comments'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:77:in `map'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:77:in `new_comments'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/formatter/git_formatter.rb:7:in `format'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:69:in `block in run'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:68:in `each'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto.rb:68:in `run'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:66:in `block in run'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:64:in `chdir'
  /usr/local/bundle/gems/pronto-0.11.0/lib/pronto/cli.rb:64:in `run'
  /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/pronto-0.11.0/bin/pronto:6:in `<top (required)>'
  /usr/local/bundle/bin/pronto:23:in `load'
  /usr/local/bundle/bin/pronto:23:in `<top (required)>'
```

For information, those are the used versions:

```bash
pronto (0.11.0)
pronto-brakeman (0.11.0)
  brakeman (>= 3.2.0)
  pronto (~> 0.11.0)
pronto-bundler_audit (0.6.0)
  bundler-audit (~> 0)
  pronto (~> 0)
pronto-fasterer (0.11.0)
  fasterer (~> 0.7.1)
  pronto (~> 0.11.0)
pronto-flay (0.11.0)
  flay (~> 2.8)
  pronto (~> 0.11.0)
pronto-reek (0.11.0)
  pronto (~> 0.11.0)
  reek (>= 4.2, < 7.0)
pronto-rubocop (0.11.1)
  pronto (~> 0.11.0)
  rubocop (>= 0.63.1, < 2.0)
```

Any idea ? Thanks in advance.

**Comment by pdobb** [comment]
It looks like pronto v0.11.0 (released 1/30/2011) has changed some of their internal APIs which this gem uses. Easy fix for you for now would be to lock pronto to 0.10.0 if that's an option for you. I no longer have a coding environment so don't expect I'll be able to fix these issues any time soon (or maybe ever).

**Comment by pdobb** [comment]
Note that I've updated the README with a "looking for a new maintainer" message.

**Comment by pdobb** [comment]
Hi, I've just pushed v0.7.0 of this gem to rubygems. If you are still using the gem, please let me know if my changes in 0.7.0 help this issue. I made a guess at a fix as I don't have a means of testing right now. Thanks.
